{
 "title": "TFG Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total number of interactions",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT * FROM interaction",
     "rawQueryText": "SELECT * FROM interaction",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total number of incomplete interactions",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryText": "SELECT \"int_id\" FROM interaction\nWHERE decisionTwo IS NULL",
     "rawQueryText": "SELECT \"int_id\" FROM interaction\nWHERE decisionTwo IS NULL",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "First decision - Would you like a T-Shirt for 1 euro?",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"dec1Si\", \"dec1No\" FROM stats",
     "rawQueryText": "SELECT \"dec1Si\", \"dec1No\" FROM stats",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Second decision - Do you still want to buy this T-Shirt?",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"dec2Si\", \"dec2No\" FROM stats",
     "rawQueryText": "SELECT \"dec2Si\", \"dec2No\" FROM stats",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Incomplete interactions after selecting 'YES'",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT \"int_id\", \"decisionOne\", \"decisionTwo\" FROM interaction\nWHERE decisionTwo IS NULL AND decisionOne = 'si'",
     "rawQueryText": "SELECT \"int_id\", \"decisionOne\", \"decisionTwo\" FROM interaction\nWHERE decisionTwo IS NULL AND decisionOne = 'si'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Incomplete interactions after selecting 'NO'",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT \"int_id\", \"decisionOne\", \"decisionTwo\" FROM interaction\nWHERE decisionTwo IS NULL AND decisionOne = 'no'",
     "rawQueryText": "SELECT \"int_id\", \"decisionOne\", \"decisionTwo\" FROM interaction\nWHERE decisionTwo IS NULL AND decisionOne = 'no'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Elapsed time throughout interaction",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'Segundos por Interacción'\nFROM interaction;",
     "rawQueryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'Segundos por Interacción'\nFROM interaction;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Elapsed seconds of incomplete interaction (after video playback)",
   "type": "bargauge",
   "description": "Este gráfico muestra la hora incial, la hora final y el tiempo en segundos de las interacciones sin terminar donde el usuario se fue durante la reproducción del video.",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'timeDiff'\nFROM interaction\nWHERE timeDiff >= 35 AND decisionTwo IS NULL",
     "rawQueryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'timeDiff'\nFROM interaction\nWHERE timeDiff >= 35 AND decisionTwo IS NULL",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Elapsed seconds of incomplete interaction (before video playback)",
   "type": "bargauge",
   "description": "Este gráfico muestra la hora incial, la hora final y el tiempo en segundos de las interacciones sin terminar donde el usuario se fue durante la reproducción del video.",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "queryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'timeDiff'\nFROM interaction\nWHERE timeDiff <= 35 AND decisionTwo IS NULL",
     "rawQueryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'timeDiff'\nFROM interaction\nWHERE timeDiff <= 35 AND decisionTwo IS NULL",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Average interaction time in seconds",
   "type": "bargauge",
   "description": "Este gráfico muestra la hora incial, la hora final y el tiempo en segundos de las interacciones sin terminar donde el usuario se fue durante la reproducción del video.",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'timeDiff'\nFROM interaction",
     "rawQueryText": "SELECT iniTime, endTime, ROUND((julianday(endTime) - julianday(iniTime)) * 86400) AS 'timeDiff'\nFROM interaction",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}